m

diff --git a/Notes-Shell_Scripting b/Notes-Shell_Scripting
--- a/Notes-Shell_Scripting
+++ b/Notes-Shell_Scripting
@@ -183,10 +183,101 @@ else
         echo " You are Failed!!!"
 fi
 
+2. ELIF (IF ELSE NESTED CONDITION):
 
-EQUAL                                   -eq  OR ==
+                read -p "How many marks you got in maths??" math
+
+                if [[ $math -lt 33  ]]
+                then
+                        echo " You FAILED!!"
+                elif [[ $math -lt 60  ]]
+                then
+                        echo " You got Second Division"
+                elif [[ $math -lt 99  ]]
+                then
+                        echo "You got First Division!!!!!!"
+                elif [[  $math -ge 99  ]]
+                then
+                        echo "You are a topper"
+                fi
+
+3. CASE
+
+                    #!/bin/bash
+                    #CASE CONCEPT
+
+                    echo "BASIC LINUX OPERATIONS"
+
+                    echo "a = To know what is today's date"
+                    echo "b = To know your os name & details"
+                    echo "c = To know your uptime"
+                    echo "d = To check disk management"
+
+                    read choice
+
+                    case $choice in
+                            a) date;;
+                            b) cat /etc/os-release;;
+                            c) uptime;;
+                            d)
+                                    df -hT
+
+                                    echo " looking for fdisk"
+
+                                    fdisk -l;;
+
+                            *) echo "Please provide correct input"
+                    esac
+
+---------------------------------------------------------------------------------------------------------------------
+
+LOGICAL OPERATORS (AND , OR , NOT)      && , || , !
+
+condition1 && condition2        -- If both conditions are true then true otherwise false
+
+condition1 || condition2        -- If any of the condition is true then it is true
+
+condition1!                     -- If condition1 is true then it is false and vice versa
+
+----------------------------------------------------------------------------------------------------------------------
+
+EQUAL                                   -eq(for numeric values)  OR ==(for string values)
 GREATER THAN EQUAL TO                   -ge
 LESS THAN EQUAL TO                      -le
 NOT EQUAL TO                            -ne  OR !=
 GREATER THAN                            -gt
 LESS THAN                               -lt
+
+------------------------------------------------------------------------------------------------------------------------
+
+USE CONDITIONAL OPERATOR IF ELSE IN SHORT FORM
+
+                                        read -p "What's your age?" age
+
+                                        [[ $age -ge 18 ]] && echo "Adult" || echo "Minor"
+
+--------------------------------------------------------------------------------------------------------------------------
+
+LOOPS
+
+1. for loop
+
+                        Example 1:
+                            for i in {1..30}
+                            do
+                                    echo "$i"
+                            done
+
+                            for name in ram shyam raju maju monu sonu
+                            do
+                                    echo "Name is $name"
+
+                            done
+                        Example 2:
+                            myarray=( 1 2 3 4 5 6 7 8 9 q w e r t y u i )
+
+                            length=${#myarray[*]}
+                            for (( i=0;i<$length;i++))
+                            do
+                                    echo " Value of my array is ${myarray[$i]}"
+                            done
